# command for installing docker-compose
# sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose

version: '3.8'
services:
  java-maven-app:
    image: {{ image_name }} # adjust {{ image_name }} also ref in Jenkinsfile
    ports:
      - "8080:8080"